### ISSUE TITLE
Partial Big Bank Example

### ISSUE THREAD

**Issue by ilaif** [Midnighter/structurizr-python#16]
Implement the majority of the big bank use cases

**Comment by yt-ms** [comment]
What's left to do before this issue can be closed?

**Comment by yt-ms** [comment]
BTW, I notice that we're not setting the IDs in big_bank.py to match [big-bank-plc.dsl](https://github.com/structurizr/dsl/blob/master/examples/big-bank-plc.dsl).  I'm happy to fix that if you want as it helps with some other stuff I'm doing.  Should I just raise a PR against this issue?

**Comment by Midnighter** [comment]
@ilaif you're more into this one, any opinions?

**Comment by ilaif** [comment]
@yt-ms What IDs are you referring to? Feel free to open a PR and we'll take a look!

**Comment by yt-ms** [comment]
I wasn't sure whether to update `BigBank.json` to match.  Let me know if you think I should.

**Comment by yt-ms** [comment]
@ilaif could you have a look at https://github.com/Midnighter/structurizr-python/pull/30 and let me know what you think please?
