### ISSUE TITLE
pip install fails on Linux

### ISSUE THREAD

**Issue by theyweresuited** [Midnighter/structurizr-python#24]
#### Problem description

Please explain:
What & how: Tried to install structurizr-python using the pip instructions on the github repo
Why: could not install it:

pip install --pre structurizr-python seems to be failing on Linux:

Could not find a version that satisfies the requirement structurizr-python (from versions: )
No matching distribution found for structurizr-python

**Comment by Midnighter** [comment]
Hey,

structurizr-python is only intended for Python 3.6 or later, could that be an issue? If that's not it, please provide the full error log.

**Comment by Midnighter** [comment]
We have released full versions since then. Please try again and let me know in case you still have problems. Closing for now.
