### ISSUE TITLE
Element.relationships and get_relationships should stay consistent

### ISSUE THREAD

**Issue by yt-ms** [Midnighter/structurizr-python#31]
#### Problem description

Whilst working with a model and its elements, it is easy to end up in a situation where `Element.relationships` and the results of the various `Element.get_*_relationships` methods are not consistent, which may lead to unexpected behaviour.

#### Code Sample

```python
from structurizr.model import Model
model = Model()
sys1 = model.add_software_system(name="sys1")
sys2 = model.add_software_system(name="sys2")
sys3 = model.add_software_system(name="sys3")
sys4 = model.add_software_system(name="sys4")
sys1.add_relationship(source=sys1, destination=sys2, description="uses")
print("sys1.relationships:      ", sys1.relationships)               # Has the new relationship with no ID
print("sys1.get_relationships():", list(sys1.get_relationships()))   # Empty
print("sys2.relationships:      ", sys2.relationships)               # Empty
print("sys2.get_relationships():", list(sys2.get_relationships()))   # Empty
print()

sys3.uses(sys4, "uses")
print("sys3.relationships:      ", sys3.relationships)               # Has the new relationship with an ID
print("sys3.get_relationships():", list(sys3.get_relationships()))   # Has the new relationship with an ID
print("sys4.relationships:      ", sys4.relationships)               # Empty
print("sys4.get_relationships():", list(sys4.get_relationships()))   # Has the new relationship with an ID
```

Output:
```
sys1.relationships:       {Relationship(id=)}
sys1.get_relationships(): []
sys2.relationships:       set()
sys2.get_relationships(): []

sys3.relationships:       {Relationship(id=5)}
sys3.get_relationships(): [Relationship(id=5)]
sys4.relationships:       set()
sys4.get_relationships(): [Relationship(id=5)]
```

Also need to look at `Model.add_relationship()` which can construct new relationships but doesn't add them to either the source or destination element.

### Context

<details>

```
System Information
==================
OS         Windows
OS-release      10
Python       3.7.5

Package Versions
================
depinfo                1.5.4
httpx                 0.15.3
ordered-set              3.1
pip                   20.2.3
pydantic               1.6.1
python-dotenv         0.14.0
setuptools            41.2.0
structurizr-python 0+unknown
```

</details>

**Comment by Midnighter** [comment]
Yes, the business logic is incomplete/inconsistent in these. Could you open a branch where you add your example above and convert it into a proper integration test, please? Then we could work against that.

**Comment by yt-ms** [comment]
Yep, sure.

**Comment by yt-ms** [comment]
Looking in `Model._add_relationship()`, it looks like the expected behaviour is that relationships should added to `Element.relationships` for outbound (efferent) relationships only.  This makes sense in terms of consistency with the serialised form as you don't want to serialise the same relationship twice.  I'm wondering however whether if `Element.relationships` is purely for (de)serialisation purposes then this could be achieved by indirecting to the model instead so there could be no inconsistency.
