### ISSUE TITLE
Add support for Python 3.9

### ISSUE THREAD

**Issue by yt-ms** [Midnighter/structurizr-python#34]
### Checklist

- [X] There are [no similar issues or pull requests](https://github.com/Midnighter/structurizr-python/issues) for this yet.

**Comment by yt-ms** [comment]
FYI, I just cloned into a new 3.9 env and tox ran fine.

**Comment by Midnighter** [comment]
Yeah, I don't foresee any issues with 3.9. Will add to tox and GitHub actions ASAP.
