### ISSUE TITLE
Improve syntax for the client locking a workspace as a context manager

### ISSUE THREAD

**Issue by yt-ms** [Midnighter/structurizr-python#62]
### Checklist

- [X] There are [no similar issues or pull requests](https://github.com/Midnighter/structurizr-python/issues) for this yet.

### Is your feature related to a problem? Please describe it.

Currently, you can lock a workspace with syntax like this:
```python
    client = StructurizrClient(settings=settings)
    with client:
        client.put_workspace(workspace)
```
This is cool, but a little unintuitive that it's actually taking a lock out.  I think it would be better to be more explicit about what's going on:
```python
    client = StructurizrClient(settings=settings)
    with client.lock():
        client.put_workspace(workspace)
```

I can't decide whether it is better to have `lock` as a method or a property, but am leaning toward method as shown.

**Comment by Midnighter** [comment]
I agree with it being a method. To me that's much clearer because you are performing an action - _locking_ the workspace - and not accessing a property. I'm now wondering if it should be `.lock()` or `.lock_workspace()`...

**Comment by yt-ms** [comment]
Well - `.lock_workspace()` would be consistent with `get_workspace()` and `put_workspace()`, but it already exists.  Not sure whether we want to make it so the _only_ way to lock/unlock is through a context manager.

**Comment by Midnighter** [comment]
No, you're right. It's better if those methods continue to exist separately.
