### ISSUE TITLE
Problem with adding a person to the existing workspace

### ISSUE THREAD

**Issue by gvelimir** [Midnighter/structurizr-python#85]
I've been trying to integrate Structurizr into a Python script, but it seems it has some problems I could not figure out so far.

I created a dummy empty workspace on Structurizr and when trying to connect and add elements, it fails on adding a person.

Line that fails:
```
user = model.add_person("User", "A user of my software system.")
```
Error stack:
```
Traceback (most recent call last):
  File "/snap/pycharm-community/252/plugins/python-ce/helpers/pydev/pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/snap/pycharm-community/252/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/velimir/smart_voucher_selection/structurizr_init.py", line 13, in <module>
    kam_user = model.add_person("User", "A user of my software system.")
TypeError: add_person() takes from 1 to 2 positional arguments but 3 were given
python-BaseException
```

**Comment by Midnighter** [comment]
Hi there,

I am sorry that the documentation is sorely lacking. In this case, the method `add_person` is defined as:

```py
def add_person(self, person=None, **kwargs)
```

so you either need to provide a `Person` instance or use keyword arguments only. Try

```py
user = model.add_person(name="User", description="A user of my software system.")
```

You may find it very helpful to browse the examples, such as [the financial risk system](https://github.com/Midnighter/structurizr-python/blob/devel/examples/financial_risk_system.py).

**Comment by Midnighter** [comment]
This issue looks resolved from my perspective. Please feel free to re-open if this continues to be a problem for you.
