### ISSUE TITLE
Problem with creating a system context view

### ISSUE THREAD

**Issue by gvelimir** [Midnighter/structurizr-python#86]
When trying to create a system context view and add an already created software system (using the same demo for financial risk system), I experience problems on this line:
```
    contextView = views.create_system_context_view(
        software_system=financial_risk_system,
        key="Context",
        description=(
            "An example System Context diagram for the Financial Risk System "
            "architecture kata."
        ),
    )
```

The error i got is the following:
```
svs_software_system=SoftwareSystem(id=2, name=Financial Risk System)
```

**Comment by Midnighter** [comment]
Sorry, that does not look like an error to me. So I'm not sure what is going wrong for you.

**Comment by gvelimir** [comment]
Sorry copy/paste mistake. Anyway i managed to solve the problem, it was due to the inappropriate brackets usage. Thx anyway.
